ItemNames:
	db "Master Ball@"
	db "Ultra Ball@"
	db "Great Ball@"
	db "Poké Ball@"
	db "TOWN MAP@"
	db "SADDLE@"
	db "?????@"
	db "SAFARI BALL@"
	db "PokéDEX@"
	db "Moon Stone@"
	db "Pecha Berry@"
	db "BRN Berry@"
	db "ICEberry@"
	db "Chesto Berry@"
	db "Cheri Berry@"
	db "Full Restore@"
	db "Leftovers @"
	db "Hyper Potion@"
	db "Moomoo Milk@"
	db "Salve@"
	db "BOULDERBADGE@"
	db "CASCADEBADGE@"
	db "THUNDERBADGE@"
	db "RAINBOWBADGE@"
	db "SOULBADGE@"
	db "MARSHBADGE@"
	db "VOLCANOBADGE@"
	db "EARTHBADGE@"
	db "Escape Rope@"
	db "Repel@"
	db "OLD AMBER@"
	db "Fire Stone@"
	db "Thunderstone@"
	db "Water Stone@"
	db "HP UP@"
	db "PROTEIN@"
	db "IRON@"
	db "CARBOS@"
	db "CALCIUM@"
	db "Rare Candy@"
	db "Dome Fossil@"
	db "Helix Fossil@"
	db "Secret Key@"
	db "SnagB@"
	db "VOUCHER@"
	db "X ACCURACY@"
	db "Leaf Stone@"
	db "CARD KEY@"
	db "Nugget@"
	db "NO UP@"
	db "Poké Doll@"
	db "Lum Berry@";full heal
	db "Revive@"
	db "MAX Revive@"
	db "GUARD Spec.@"
	db "SUPER Repel@"
	db "MAX Repel@"
	db "DIRE Hit@"
	db "COIN@"
	db "Fresh Water@"
	db "Soda Pop@"
	db "Lemonade@"
	db "S.S.TICKET@"
	db "GOLD TEETH@"
	db "X ATTACK@"
	db "X DEFEND@"
	db "X SPEED@"
	db "X SPECIAL@"
	db "COIN CASE@"
	db "OAK's PARCEL@"
	db "ITEMFINDER@"
	db "SILPH SCOPE@"
	db "Poké Flute@"
	db "LIFT KEY@"
	db "EXP.ALL@"
	db "OLD ROD@"
	db "GOOD ROD@"
	db "SUPER ROD@"
	db "PP UP@"
	db "ETHER@"
	db "MAX ETHER@"
	db "ELIXER@"
	db "MAX ELIXER@"
	db "B2F@"
	db "B1F@"
	db "1F@"
	db "2F@"
	db "3F@"
	db "4F@"
	db "5F@"
	db "6F@"
	db "7F@"
	db "8F@"
	db "9F@"
	db "10F@"
	db "11F@"
	db "B4F@"
	db "Sun Stone@"
	db "Frost Stone@"
	db "Love Stone@"
	db "Shiny Stone@";most of this and below not currently in use
	db "King's Rock@"
	db "Steel Coat@"
	db "Quick Claw@"
	db "Evolite@"
;	db "Lucky Egg@";
	db "Sitrus Berry@";except berries~
	db "Oran Berry@"